import { APIListResponse, Bot } from '@trading/types';

const mockItem: Bot = {
  name: 'Test item',
  platform: 'Binance',
  tradingAccountId: 11,
  tradingAccountName: 'Test',
  strategy: 'Grid',
  instrument: 'BTC/USDT',
  isRunning: false,
  status: 'Initializing',
  statusAlias: 'Initializing',
  statusColor: '#0B9F43',
  creationTime: '2023-11-13T09:00:27.6933333Z',
  lastRunStart: null,
  lastRunEnd: null,
  lastRunDurationTimestamp: 0,
  lastRunDuration: '0',
  lastStatusUpdate: '0',
  lastOrderDate: null,
  statistics: {
    coinForBalance: 'BTC',
    roi: 0,
    pnl: 0,
    pnlUp: null,
    hourlyPnl: 0,
    turnover: 0,
    orders: 0,
    errors: 0,
    runs: 0,
    noControlOrdersCount: 0,
    noControlOrdersSize: 0,
    noControlOrdersPnl: 0,
    commission: 0,
    pnlInvestment: 0,
    pnlInvestmentUp: null,
    pnlTotal: 0,
    pnlTotalUp: null,
    roiInvestment: 0,
    roiTotal: 0,
    matchedOrders: 0,
  },
  lastOrderDurationTimestamp: 0,
  lastOrderDuration: '0',
  isActionsDisabled: false,
  id: 1,
  start: '2023-11-13T09:00:27.6933333Z',
  uptimeTimestamp: 10,
  uptimeDuration: '2023-11-14T09:00:27.6933333Z',
  currentlyInUsePercents: 0,
  averageOrderSize: 0,
  buildNumber: '',
  isLastVersion: false,
  weightedAssetPrice: 0,
  weightedAssetBuyPrice: 0,
  weightedAssetSellPrice: 0,
  weightedAssetBuyVolume: 0,
  weightedAssetSellVolume: 0,
  baseCurrency: '',
  quoteCurrency: '',
  uptimeDurationTimestamp: 0,
  mobileStatistics: null,
  formattedOrderSize: '',
  lastNotificationTime: null,
  lastNotificationTitle: null,
  lastNotificationText: null,
  maxInWorkPercents: 0,
  maxInWork: 0,
  currentInWork: 0,
};

type CreateMockData = (
  itemCount: number,
  totalCount?: number,
) => APIListResponse<Bot>;

export const createMockData: CreateMockData = (
  itemsCount,
  totalCount = 25,
) => ({
  result: {
    totalCount,
    items: new Array(itemsCount).fill({}).map((_value, index) => ({
      ...mockItem,
      id: index + 1,
    })),
  },
});
