import { GraphStatistics } from '@/trading/types';

export const data: GraphStatistics = {
  data: [
    {
      rebalancing: {
        sold: 20201.41,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 51302.26,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 5,
        failures: 2,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 5,
            failures: 2,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5626,
      matchedOrders: 2859,
      pnlFromInitial: null,
      pnl: 362.28,
      cumulativePNL: 362.28,
      turnover: 1550951,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 179.86,
      cumulativePnlInvestment: 179.86,
      pnlTotal: 542.14,
      cumulativePnlTotal: 542.14,
      timestamp: '2024-09-26T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 46229.34,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 1,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 1,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5108,
      matchedOrders: 2702,
      pnlFromInitial: null,
      pnl: 171,
      cumulativePNL: 533.28,
      turnover: 1540500,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 52.55,
      cumulativePnlInvestment: 232.41,
      pnlTotal: 223.55,
      cumulativePnlTotal: 765.69,
      timestamp: '2024-09-27T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 21434.89,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 19137.48,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 0,
        serviceOperations: 2,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 0,
            serviceOperations: 2,
          },
        ],
      },
      allOrders: 4307,
      matchedOrders: 1978,
      pnlFromInitial: null,
      pnl: 210.35,
      cumulativePNL: 743.63,
      turnover: 1953538,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 1.91,
      cumulativePnlInvestment: 234.32,
      pnlTotal: 212.26,
      cumulativePnlTotal: 977.95,
      timestamp: '2024-09-28T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 59596.73,
        sellOrders: 3,
        sellingBotNames: ['Test bot'],
        bought: 21464.39,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 6,
        failures: 0,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 6,
            failures: 0,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7145,
      matchedOrders: 3541,
      pnlFromInitial: null,
      pnl: 87.7,
      cumulativePNL: 831.33,
      turnover: 2941056,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -7.67,
      cumulativePnlInvestment: 226.65,
      pnlTotal: 80.03,
      cumulativePnlTotal: 1057.98,
      timestamp: '2024-09-29T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 117129.79,
        sellOrders: 6,
        sellingBotNames: ['Test bot'],
        bought: 72433.79,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 10,
        failures: 0,
        serviceOperations: 10,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 10,
            failures: 0,
            serviceOperations: 10,
          },
        ],
      },
      allOrders: 7029,
      matchedOrders: 3272,
      pnlFromInitial: null,
      pnl: -2487.12,
      cumulativePNL: -1655.79,
      turnover: 2059127,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -214.48,
      cumulativePnlInvestment: 12.17,
      pnlTotal: -2701.6,
      cumulativePnlTotal: -1643.62,
      timestamp: '2024-09-30T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 82593.99,
        sellOrders: 4,
        sellingBotNames: ['Test bot'],
        bought: 84931.1,
        buyOrders: 5,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 12,
        failures: 6,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 12,
            failures: 6,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7383,
      matchedOrders: 3822,
      pnlFromInitial: null,
      pnl: -2448.09,
      cumulativePNL: -4103.88,
      turnover: 2754208,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -192.56,
      cumulativePnlInvestment: -180.39,
      pnlTotal: -2640.65,
      cumulativePnlTotal: -4284.27,
      timestamp: '2024-10-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 16194.43,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 49104.92,
        buyOrders: 3,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 0,
        serviceOperations: 4,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 0,
            serviceOperations: 4,
          },
        ],
      },
      allOrders: 2213,
      matchedOrders: 956,
      pnlFromInitial: null,
      pnl: -262.68,
      cumulativePNL: -4366.56,
      turnover: 599416,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 70.56,
      cumulativePnlInvestment: -109.83,
      pnlTotal: -192.12,
      cumulativePnlTotal: -4476.39,
      timestamp: '2024-10-02T00:00:00Z',
    },
  ],
  aggregationPeriod: 'Daily',
};
