import { Bot, StatusType } from '@/trading/types';

export type SingleBot = Omit<
  Bot,
  'instrument' | 'start' | 'uptimeTimestamp' | 'baseCurrency' | 'quoteCurrency'
>;

export type AllBots = {
  totalCount: number;
  items: Array<SingleBot>;
};

const singleBotMock: SingleBot = {
  id: 1,
  name: 'Test bot',
  platform: 'Binance',
  tradingAccountId: 10,
  tradingAccountName: 'Test account name',
  strategy: 'Scalping',
  isRunning: false,
  status: 'Running',
  statusAlias: 'Running' as StatusType,
  statusColor: '#0B9F43',
  creationTime: '2024-06-26T07:32:29.2674655Z',
  lastRunStart: '2024-10-09T15:31:31.7926905Z',
  lastRunEnd: null,
  lastRunDurationTimestamp: 3198,
  lastRunDuration: '00:53:18',
  uptimeDurationTimestamp: 3198,
  uptimeDuration: '00:53:18',
  lastOrderDate: '2024-10-09T16:18:47Z',
  statistics: {
    coinForBalance: 'BTC',
    roi: 84,
    pnl: 0.870346,
    pnlUp: false,
    hourlyPnl: 0.000353,
    turnover: 864.8066,
    orders: 218206,
    matchedOrders: 0,
    errors: 0,
    runs: 0,
    noControlOrdersCount: 21,
    noControlOrdersSize: 0.0255,
    noControlOrdersPnl: -0.000948,
    commission: 0,
    pnlInvestment: 0.002601,
    pnlInvestmentUp: false,
    pnlTotal: 0.872946,
    pnlTotalUp: false,
    roiInvestment: 0.25,
    roiTotal: 84,
  },
  mobileStatistics: null,
  lastOrderDurationTimestamp: 363,
  lastOrderDuration: '00:06:03',
  isActionsDisabled: true,
  formattedOrderSize: '',
  lastStatusUpdate: '2024-10-09T16:16:03.6501017Z',
  lastNotificationTime: null,
  lastNotificationTitle: null,
  lastNotificationText: null,
  averageOrderSize: 0.00782,
  currentlyInUsePercents: 4.3,
  maxInWorkPercents: 280,
  isLastVersion: false,
  buildNumber: '20240903.2',
  maxInWork: 2.91309,
  currentInWork: 0.044283,
  weightedAssetPrice: 0,
  weightedAssetBuyPrice: 0,
  weightedAssetSellPrice: 0,
  weightedAssetBuyVolume: 0,
  weightedAssetSellVolume: 0,
};

export const allBotsMock: AllBots = {
  totalCount: 12,
  items: [
    {
      ...singleBotMock,
      id: 1,
      name: 'Test Bot 1',
      platform: 'Binance',
      strategy: 'Scalping',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 2,
      name: 'Test Bot 2',
      platform: 'ByBit',
      strategy: 'Grid2',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 3,
      name: 'Test Bot 3',
      platform: 'Binance',
      strategy: 'Grid2',
      status: 'Running',
      statusAlias: 'Running',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 4,
      name: 'Test Bot 4',
      platform: 'Binance',
      strategy: 'Scalping',
      status: 'Running',
      statusAlias: 'Running',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 5,
      name: 'Test Bot 5',
      platform: 'Binance',
      status: 'Stopped',
      statusAlias: 'Stopped',
    },
    {
      ...singleBotMock,
      id: 6,
      name: 'Test Bot 6',
      status: 'Stopped',
      statusAlias: 'Stopped',
    },
    {
      ...singleBotMock,
      id: 7,
      name: 'Test Bot 7',
      platform: 'ByBit',
      strategy: 'Scalping',
      status: 'Running',
      statusAlias: 'Running',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 8,
      name: 'Test Bot 8',
      platform: 'ByBit',
      strategy: 'Scalping',
      status: 'Stopped',
      statusAlias: 'Stopped',
    },
    {
      ...singleBotMock,
      id: 9,
      name: 'Test Bot 9',
      platform: 'ByBit',
      strategy: 'Grid1',
      status: 'Stopped',
      statusAlias: 'Stopped',
    },
    {
      ...singleBotMock,
      id: 10,
      name: 'Test Bot 10',
      platform: 'Binance',
      strategy: 'Grid1',
      status: 'Stopped',
      statusAlias: 'Stopped',
    },
    {
      ...singleBotMock,
      id: 11,
      name: 'Test Bot 11',
      platform: 'Binance',
      strategy: 'Grid1',
      isRunning: true,
    },
    {
      ...singleBotMock,
      id: 12,
      name: 'Test Bot 12',
      platform: 'ByBit',
      isRunning: true,
    },
  ],
};

export const botInformationByIdMock: Record<
  number,
  { pnl: number; roi: number }
> = {
  1: { pnl: -14.44, roi: -0.35 },
  2: { pnl: -15.9, roi: -0.25 },
  3: { pnl: -19, roi: -0.23 },
  4: { pnl: -5.24, roi: -0.12 },
  5: { pnl: 7.03, roi: 0.1 },
  6: { pnl: 4.08, roi: 0.12 },
  7: { pnl: 7.22, roi: 0.14 },
  8: { pnl: 13.66, roi: 0.13 },
  9: { pnl: 22.34, roi: 0.13 },
  10: { pnl: 10.06, roi: 0.15 },
  11: { pnl: 6.36, roi: 0.15 },
  12: { pnl: 6.32, roi: 0.16 },
};
