export const dashboardIndicatorsMock = {
  indicators: {
    totalStaff: 63,
    fte: 55.85,
    utilization: 95,
    resourcesOnBench: 0,
    seniority: 93.93,
    tenure: 7.4,
    staffTurnover: 0,
  },
  diagrams: {
    staffType: {
      production: 44,
      productionColor: '#4CBFFD',
      administrative: 19,
      administrativeColor: '#FDC67D',
      productionPercentage: 70,
      administrativePercentage: 30,
    },
    workSchedule: {
      fullTime: 53,
      fullTimeColor: '#FF7379',
      partTime: 10,
      partTimeColor: '#99E176',
      fullTimePercentage: 84,
      partTimePercentage: 16,
    },
    employmentType: {
      contractors: 11,
      contractorsColor: '#2CBB97',
      staff: 52,
      staffColor: '#F9F789',
      contractorsPercentage: 17,
      staffPercentage: 83,
    },
    genderType: {
      male: 48,
      maleColor: '#5B8DEC',
      female: 15,
      femaleColor: '#F463EA',
      others: 0,
      othersColor: '#D2D4DB',
      malePercentage: 76,
      femalePercentage: 24,
      othersPercentage: 0,
    },
  },
};
