export const data = {
  data: [
    {
      rebalancing: {
        sold: 6630.53,
        sellOrders: 2,
        sellingBotNames: ['Test bot'],
        bought: 7379.2,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 2720,
      matchedOrders: 1719,
      pnlFromInitial: null,
      pnl: -25.51,
      cumulativePNL: -25.51,
      turnover: 236978,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -25.51,
      cumulativePnlTotal: -25.51,
      timestamp: '2024-09-03T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 26264.27,
        sellOrders: 2,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 2,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 2,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 3034,
      matchedOrders: 1797,
      pnlFromInitial: null,
      pnl: 57998.57,
      cumulativePNL: 57973.05,
      turnover: 712870,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 57998.57,
      cumulativePnlTotal: 57973.05,
      timestamp: '2024-09-04T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 82128.05,
        sellOrders: 2,
        sellingBotNames: ['Test bot'],
        bought: 105848.11,
        buyOrders: 3,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 2,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 2,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 3209,
      matchedOrders: 1811,
      pnlFromInitial: null,
      pnl: -3184.6,
      cumulativePNL: 54788.45,
      turnover: 1515142,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -3184.6,
      cumulativePnlTotal: 54788.45,
      timestamp: '2024-09-05T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 1433.04,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 25059.83,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 2,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 2,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 2156,
      matchedOrders: 1168,
      pnlFromInitial: null,
      pnl: -3380.91,
      cumulativePNL: 51407.54,
      turnover: 884962,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -3380.91,
      cumulativePnlTotal: 51407.54,
      timestamp: '2024-09-06T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -9.3,
      cumulativePNL: 51398.24,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -9.3,
      cumulativePnlTotal: 51398.24,
      timestamp: '2024-09-07T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -46.43,
      cumulativePNL: 51351.81,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -46.43,
      cumulativePnlTotal: 51351.81,
      timestamp: '2024-09-08T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -119.37,
      cumulativePNL: 51232.44,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -119.37,
      cumulativePnlTotal: 51232.44,
      timestamp: '2024-09-09T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 22485.95,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 50321.98,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 0,
        serviceOperations: 2,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 0,
            serviceOperations: 2,
          },
        ],
      },
      allOrders: 3205,
      matchedOrders: 1904,
      pnlFromInitial: null,
      pnl: -351,
      cumulativePNL: 50881.43,
      turnover: 1252708,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -351,
      cumulativePnlTotal: 50881.43,
      timestamp: '2024-09-10T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 2648,
      matchedOrders: 1540,
      pnlFromInitial: null,
      pnl: -180.45,
      cumulativePNL: 50700.98,
      turnover: 256107,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -180.45,
      cumulativePnlTotal: 50700.98,
      timestamp: '2024-09-11T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 7,
      matchedOrders: 7,
      pnlFromInitial: null,
      pnl: 616.48,
      cumulativePNL: 51317.46,
      turnover: 524,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 616.48,
      cumulativePnlTotal: 51317.46,
      timestamp: '2024-09-12T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 116616.46,
        sellOrders: 3,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 104449.6,
        buyOrders: 4,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 2,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot configuration 1',
            runs: 2,
            failures: 2,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 1999.03,
      cumulativePNL: 53316.48,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 1999.03,
      cumulativePnlTotal: 53316.48,
      timestamp: '2024-09-13T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 19254.34,
        sellOrders: 2,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 44313.78,
        buyOrders: 1,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot configuration 1',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -496.93,
      cumulativePNL: 52819.56,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -496.93,
      cumulativePnlTotal: 52819.56,
      timestamp: '2024-09-14T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 151811.75,
        sellOrders: 4,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 116935.64,
        buyOrders: 3,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -707.9,
      cumulativePNL: 52111.66,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -707.9,
      cumulativePnlTotal: 52111.66,
      timestamp: '2024-09-15T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 43601.95,
        sellOrders: 1,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 99519.49,
        buyOrders: 5,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: -682.2,
      cumulativePNL: 51429.46,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -682.2,
      cumulativePnlTotal: 51429.46,
      timestamp: '2024-09-16T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 195475.01,
        sellOrders: 7,
        sellingBotNames: ['Test bot configuration 1', 'Test bot'],
        bought: 228927.63,
        buyOrders: 6,
        buyingBotNames: ['Test bot configuration 1', 'Test bot'],
      },
      keeperRuns: {
        totalRuns: 8,
        failures: 4,
        serviceOperations: 4,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 0,
            serviceOperations: 4,
          },
          {
            botName: 'Test bot configuration 1',
            runs: 4,
            failures: 4,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 1824,
      matchedOrders: 904,
      pnlFromInitial: null,
      pnl: -1465.85,
      cumulativePNL: 49963.61,
      turnover: 1147484,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 20.01,
      cumulativePnlInvestment: 20.01,
      pnlTotal: -1445.84,
      cumulativePnlTotal: 49983.62,
      timestamp: '2024-09-17T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 94270.88,
        sellOrders: 4,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 121864.78,
        buyOrders: 4,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot configuration 1',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 2173,
      matchedOrders: 1479,
      pnlFromInitial: null,
      pnl: 888.57,
      cumulativePNL: 50852.18,
      turnover: 1199782,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 90.87,
      cumulativePnlInvestment: 110.88,
      pnlTotal: 979.44,
      cumulativePnlTotal: 50963.06,
      timestamp: '2024-09-18T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 34842.5,
        sellOrders: 2,
        sellingBotNames: ['Test bot', 'Test bot configuration 1'],
        bought: 188575.42,
        buyOrders: 6,
        buyingBotNames: ['Test bot', 'Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 5,
        failures: 3,
        serviceOperations: 2,
        botRuns: [
          {
            botName: 'Test bot configuration 1',
            runs: 3,
            failures: 3,
            serviceOperations: 0,
          },
          {
            botName: 'Test bot',
            runs: 2,
            failures: 0,
            serviceOperations: 2,
          },
        ],
      },
      allOrders: 4621,
      matchedOrders: 2198,
      pnlFromInitial: null,
      pnl: -85.53,
      cumulativePNL: 50766.65,
      turnover: 1561691,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 150.88,
      cumulativePnlInvestment: 261.76,
      pnlTotal: 65.35,
      cumulativePnlTotal: 51028.41,
      timestamp: '2024-09-19T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 144839.54,
        sellOrders: 7,
        sellingBotNames: ['Test bot configuration 1', 'Test bot'],
        bought: 127484.49,
        buyOrders: 7,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 14,
        failures: 3,
        serviceOperations: 11,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 12,
            failures: 1,
            serviceOperations: 11,
          },
          {
            botName: 'Test bot 2',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
          {
            botName: 'Test bot configuration 1',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 6537,
      matchedOrders: 3166,
      pnlFromInitial: null,
      pnl: -1570.33,
      cumulativePNL: 49196.32,
      turnover: 2197716,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 13.1,
      cumulativePnlInvestment: 274.86,
      pnlTotal: -1557.23,
      cumulativePnlTotal: 49471.18,
      timestamp: '2024-09-20T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 33187.6,
        sellOrders: 2,
        sellingBotNames: ['Test bot'],
        bought: 1051.4,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 3,
        failures: 0,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 3,
            failures: 0,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5114,
      matchedOrders: 2112,
      pnlFromInitial: null,
      pnl: -99,
      cumulativePNL: 49097.32,
      turnover: 1081258,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 15.44,
      cumulativePnlInvestment: 290.3,
      pnlTotal: -83.56,
      cumulativePnlTotal: 49387.62,
      timestamp: '2024-09-21T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 30169.18,
        sellOrders: 3,
        sellingBotNames: ['Test bot'],
        bought: 42975.24,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 7,
        failures: 0,
        serviceOperations: 7,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 7,
            failures: 0,
            serviceOperations: 7,
          },
        ],
      },
      allOrders: 4551,
      matchedOrders: 1855,
      pnlFromInitial: null,
      pnl: -559.8,
      cumulativePNL: 48537.51,
      turnover: 1079432,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 14.09,
      cumulativePnlInvestment: 304.39,
      pnlTotal: -545.72,
      cumulativePnlTotal: 48841.9,
      timestamp: '2024-09-22T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 2914.99,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 2898,
      matchedOrders: 1572,
      pnlFromInitial: null,
      pnl: -28.8,
      cumulativePNL: 48508.72,
      turnover: 163603,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -9.8,
      cumulativePnlInvestment: 294.58,
      pnlTotal: -38.6,
      cumulativePnlTotal: 48803.3,
      timestamp: '2024-09-23T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 60296.06,
        sellOrders: 3,
        sellingBotNames: ['Test bot'],
        bought: 123726.85,
        buyOrders: 7,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 10,
        failures: 1,
        serviceOperations: 9,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 10,
            failures: 1,
            serviceOperations: 9,
          },
        ],
      },
      allOrders: 5227,
      matchedOrders: 2853,
      pnlFromInitial: null,
      pnl: -622.05,
      cumulativePNL: 47886.67,
      turnover: 1969240,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 83.83,
      cumulativePnlInvestment: 378.41,
      pnlTotal: -538.22,
      cumulativePnlTotal: 48265.08,
      timestamp: '2024-09-24T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 69637.79,
        sellOrders: 4,
        sellingBotNames: ['Test bot'],
        bought: 18338.41,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 7,
        failures: 1,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 7,
            failures: 1,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 4522,
      matchedOrders: 2755,
      pnlFromInitial: null,
      pnl: -986.28,
      cumulativePNL: 46900.39,
      turnover: 1713309,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -109.96,
      cumulativePnlInvestment: 268.46,
      pnlTotal: -1096.24,
      cumulativePnlTotal: 47168.84,
      timestamp: '2024-09-25T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 20201.41,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 51302.26,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 5,
        failures: 2,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 5,
            failures: 2,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5626,
      matchedOrders: 2859,
      pnlFromInitial: null,
      pnl: 362.28,
      cumulativePNL: 47262.66,
      turnover: 1550951,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 179.86,
      cumulativePnlInvestment: 448.32,
      pnlTotal: 542.14,
      cumulativePnlTotal: 47710.98,
      timestamp: '2024-09-26T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 46229.34,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 1,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 1,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5108,
      matchedOrders: 2702,
      pnlFromInitial: null,
      pnl: 171,
      cumulativePNL: 47433.67,
      turnover: 1540500,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 52.55,
      cumulativePnlInvestment: 500.87,
      pnlTotal: 223.55,
      cumulativePnlTotal: 47934.53,
      timestamp: '2024-09-27T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 21434.89,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 19137.48,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 0,
        serviceOperations: 2,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 0,
            serviceOperations: 2,
          },
        ],
      },
      allOrders: 4307,
      matchedOrders: 1978,
      pnlFromInitial: null,
      pnl: 210.35,
      cumulativePNL: 47644.02,
      turnover: 1953538,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 1.91,
      cumulativePnlInvestment: 502.78,
      pnlTotal: 212.26,
      cumulativePnlTotal: 48146.8,
      timestamp: '2024-09-28T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 59596.73,
        sellOrders: 3,
        sellingBotNames: ['Test bot'],
        bought: 21464.39,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 6,
        failures: 0,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 6,
            failures: 0,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7145,
      matchedOrders: 3541,
      pnlFromInitial: null,
      pnl: 87.7,
      cumulativePNL: 47731.71,
      turnover: 2941056,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -7.67,
      cumulativePnlInvestment: 495.11,
      pnlTotal: 80.03,
      cumulativePnlTotal: 48226.83,
      timestamp: '2024-09-29T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 117129.79,
        sellOrders: 6,
        sellingBotNames: ['Test bot'],
        bought: 72433.79,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 10,
        failures: 0,
        serviceOperations: 10,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 10,
            failures: 0,
            serviceOperations: 10,
          },
        ],
      },
      allOrders: 7029,
      matchedOrders: 3272,
      pnlFromInitial: null,
      pnl: -2487.12,
      cumulativePNL: 45244.59,
      turnover: 2059127,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -214.48,
      cumulativePnlInvestment: 280.63,
      pnlTotal: -2701.6,
      cumulativePnlTotal: 45525.23,
      timestamp: '2024-09-30T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 82593.99,
        sellOrders: 4,
        sellingBotNames: ['Test bot'],
        bought: 84931.1,
        buyOrders: 5,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 12,
        failures: 6,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 12,
            failures: 6,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7383,
      matchedOrders: 3822,
      pnlFromInitial: null,
      pnl: -2448.09,
      cumulativePNL: 42796.5,
      turnover: 2754208,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -192.56,
      cumulativePnlInvestment: 88.07,
      pnlTotal: -2640.65,
      cumulativePnlTotal: 42884.57,
      timestamp: '2024-10-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 16194.43,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 49104.92,
        buyOrders: 3,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 0,
        serviceOperations: 4,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 0,
            serviceOperations: 4,
          },
        ],
      },
      allOrders: 2213,
      matchedOrders: 956,
      pnlFromInitial: null,
      pnl: -262.68,
      cumulativePNL: 42533.83,
      turnover: 599416,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 70.56,
      cumulativePnlInvestment: 158.62,
      pnlTotal: -192.12,
      cumulativePnlTotal: 42692.45,
      timestamp: '2024-10-02T00:00:00Z',
    },
  ],
  aggregationPeriod: 'Daily',
};
