export const data = {
  data: [
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 206,
      matchedOrders: 75,
      pnlFromInitial: null,
      pnl: -25.82,
      cumulativePNL: -25.82,
      turnover: 51624,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -10.5,
      cumulativePnlInvestment: -10.5,
      pnlTotal: -36.32,
      cumulativePnlTotal: -36.32,
      timestamp: '2024-10-01T11:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 552,
      matchedOrders: 131,
      pnlFromInitial: null,
      pnl: -50.23,
      cumulativePNL: -76.05,
      turnover: 57500,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -16.05,
      cumulativePnlInvestment: -26.56,
      pnlTotal: -66.29,
      cumulativePnlTotal: -102.61,
      timestamp: '2024-10-01T12:00:00Z',
    },
    {
      rebalancing: {
        sold: 25474.41,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 1,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 1,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 421,
      matchedOrders: 231,
      pnlFromInitial: null,
      pnl: -865.76,
      cumulativePNL: -941.81,
      turnover: 225418,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -85.77,
      cumulativePnlInvestment: -112.33,
      pnlTotal: -951.53,
      cumulativePnlTotal: -1054.14,
      timestamp: '2024-10-01T13:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 22052.3,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 320,
      matchedOrders: 168,
      pnlFromInitial: null,
      pnl: -1.61,
      cumulativePNL: -943.43,
      turnover: 142705,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 11.92,
      cumulativePnlInvestment: -100.41,
      pnlTotal: 10.31,
      cumulativePnlTotal: -1043.83,
      timestamp: '2024-10-01T14:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 23451.4,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 3,
        failures: 2,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 3,
            failures: 2,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 223,
      matchedOrders: 72,
      pnlFromInitial: null,
      pnl: -147.17,
      cumulativePNL: -1090.59,
      turnover: 70015,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -4.34,
      cumulativePnlInvestment: -104.75,
      pnlTotal: -151.51,
      cumulativePnlTotal: -1195.34,
      timestamp: '2024-10-01T15:00:00Z',
    },
    {
      rebalancing: {
        sold: 17071.24,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 372,
      matchedOrders: 244,
      pnlFromInitial: null,
      pnl: -508.67,
      cumulativePNL: -1599.26,
      turnover: 190991,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -55.82,
      cumulativePnlInvestment: -160.57,
      pnlTotal: -564.49,
      cumulativePnlTotal: -1759.83,
      timestamp: '2024-10-01T16:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 308,
      matchedOrders: 231,
      pnlFromInitial: null,
      pnl: -377.52,
      cumulativePNL: -1976.78,
      turnover: 237734,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -11.95,
      cumulativePnlInvestment: -172.53,
      pnlTotal: -389.47,
      cumulativePnlTotal: -2149.3,
      timestamp: '2024-10-01T17:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18089.56,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 171,
      matchedOrders: 80,
      pnlFromInitial: null,
      pnl: -5.44,
      cumulativePNL: -1982.22,
      turnover: 22350,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 8.46,
      cumulativePnlInvestment: -164.06,
      pnlTotal: 3.02,
      cumulativePnlTotal: -2146.28,
      timestamp: '2024-10-01T18:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 576,
      matchedOrders: 321,
      pnlFromInitial: null,
      pnl: -179.74,
      cumulativePNL: -2161.96,
      turnover: 278071,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -16.69,
      cumulativePnlInvestment: -180.75,
      pnlTotal: -196.43,
      cumulativePnlTotal: -2342.71,
      timestamp: '2024-10-01T19:00:00Z',
    },
    {
      rebalancing: {
        sold: 16844.63,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 487,
      matchedOrders: 287,
      pnlFromInitial: null,
      pnl: -800.52,
      cumulativePNL: -2962.48,
      turnover: 239572,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -114.32,
      cumulativePnlInvestment: -295.07,
      pnlTotal: -914.84,
      cumulativePnlTotal: -3257.55,
      timestamp: '2024-10-01T20:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 319,
      matchedOrders: 253,
      pnlFromInitial: null,
      pnl: 225.67,
      cumulativePNL: -2736.82,
      turnover: 210737,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 38.45,
      cumulativePnlInvestment: -256.61,
      pnlTotal: 264.12,
      cumulativePnlTotal: -2993.43,
      timestamp: '2024-10-01T21:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 260,
      matchedOrders: 173,
      pnlFromInitial: null,
      pnl: -67.19,
      cumulativePNL: -2804.01,
      turnover: 91089,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -18.63,
      cumulativePnlInvestment: -275.25,
      pnlTotal: -85.83,
      cumulativePnlTotal: -3079.25,
      timestamp: '2024-10-01T22:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 358,
      matchedOrders: 289,
      pnlFromInitial: null,
      pnl: 126.85,
      cumulativePNL: -2677.16,
      turnover: 239167,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 18.13,
      cumulativePnlInvestment: -257.12,
      pnlTotal: 144.97,
      cumulativePnlTotal: -2934.28,
      timestamp: '2024-10-01T23:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 208,
      matchedOrders: 132,
      pnlFromInitial: null,
      pnl: 22.61,
      cumulativePNL: -2654.55,
      turnover: 60821,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 13.78,
      cumulativePnlInvestment: -243.34,
      pnlTotal: 36.39,
      cumulativePnlTotal: -2897.89,
      timestamp: '2024-10-02T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 12068.16,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 283,
      matchedOrders: 159,
      pnlFromInitial: null,
      pnl: 24.77,
      cumulativePNL: -2629.78,
      turnover: 111770,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 30.59,
      cumulativePnlInvestment: -212.75,
      pnlTotal: 55.36,
      cumulativePnlTotal: -2842.53,
      timestamp: '2024-10-02T01:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 456,
      matchedOrders: 134,
      pnlFromInitial: null,
      pnl: 51.66,
      cumulativePNL: -2578.12,
      turnover: 86127,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 17.37,
      cumulativePnlInvestment: -195.38,
      pnlTotal: 69.03,
      cumulativePnlTotal: -2773.5,
      timestamp: '2024-10-02T02:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18612.55,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 306,
      matchedOrders: 124,
      pnlFromInitial: null,
      pnl: -33.74,
      cumulativePNL: -2611.85,
      turnover: 88644,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 15.13,
      cumulativePnlInvestment: -180.26,
      pnlTotal: -18.61,
      cumulativePnlTotal: -2792.11,
      timestamp: '2024-10-02T03:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 161,
      matchedOrders: 113,
      pnlFromInitial: null,
      pnl: -141.32,
      cumulativePNL: -2753.17,
      turnover: 53019,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -28.32,
      cumulativePnlInvestment: -208.58,
      pnlTotal: -169.64,
      cumulativePnlTotal: -2961.75,
      timestamp: '2024-10-02T04:00:00Z',
    },
    {
      rebalancing: {
        sold: 16194.43,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 256,
      matchedOrders: 128,
      pnlFromInitial: null,
      pnl: -15.74,
      cumulativePNL: -2768.91,
      turnover: 64918,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: -2.83,
      cumulativePnlInvestment: -211.41,
      pnlTotal: -18.57,
      cumulativePnlTotal: -2980.32,
      timestamp: '2024-10-02T05:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18424.22,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 320,
      matchedOrders: 94,
      pnlFromInitial: null,
      pnl: -109.52,
      cumulativePNL: -2878.44,
      turnover: 81987,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 23.92,
      cumulativePnlInvestment: -187.49,
      pnlTotal: -85.6,
      cumulativePnlTotal: -3065.92,
      timestamp: '2024-10-02T06:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 223,
      matchedOrders: 72,
      pnlFromInitial: null,
      pnl: -61.4,
      cumulativePNL: -2939.83,
      turnover: 52130,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0.92,
      cumulativePnlInvestment: -186.56,
      pnlTotal: -60.47,
      cumulativePnlTotal: -3126.4,
      timestamp: '2024-10-02T07:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: -2939.83,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: -186.56,
      pnlTotal: 0,
      cumulativePnlTotal: -3126.4,
      timestamp: '2024-10-02T08:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: -2939.83,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: -186.56,
      pnlTotal: 0,
      cumulativePnlTotal: -3126.4,
      timestamp: '2024-10-02T09:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: -2939.83,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: -186.56,
      pnlTotal: 0,
      cumulativePnlTotal: -3126.4,
      timestamp: '2024-10-02T10:00:00Z',
    },
  ],
  aggregationPeriod: 'Hourly',
};
