import { GraphStatistics } from '@/fintech/types';

export const data: GraphStatistics = {
  data: [
    {
      rebalancing: {
        sold: 20201.41,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 51302.26,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 5,
        failures: 2,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 5,
            failures: 2,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5626,
      matchedOrders: 2859,
      pnlFromInitial: null,
      turnover: 1550951,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -540.14,
      cumulativePnlTotal: -540.14,
      timestamp: '2024-09-26T00:00:00Z',
      pnl: -361.28,
      cumulativePNL: -361.28,
      pnlInvestment: -178.86,
      cumulativePnlInvestment: -178.86,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 46229.34,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 1,
        serviceOperations: 3,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 1,
            serviceOperations: 3,
          },
        ],
      },
      allOrders: 5108,
      matchedOrders: 2702,
      pnlFromInitial: null,
      turnover: 1540500,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -221.55,
      cumulativePnlTotal: -763.69,
      timestamp: '2024-09-27T00:00:00Z',
      pnl: -170,
      cumulativePNL: -532.28,
      pnlInvestment: -51.55,
      cumulativePnlInvestment: -231.41,
    },
    {
      rebalancing: {
        sold: 21434.89,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 19137.48,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 0,
        serviceOperations: 2,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 0,
            serviceOperations: 2,
          },
        ],
      },
      allOrders: 4307,
      matchedOrders: 1978,
      pnlFromInitial: null,
      turnover: 1953538,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -210.26,
      cumulativePnlTotal: -975.95,
      timestamp: '2024-09-28T00:00:00Z',
      pnl: -209.35,
      cumulativePNL: -742.63,
      pnlInvestment: -0.91,
      cumulativePnlInvestment: -233.32,
    },
    {
      rebalancing: {
        sold: 59596.73,
        sellOrders: 3,
        sellingBotNames: ['Test bot'],
        bought: 21464.39,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 6,
        failures: 0,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 6,
            failures: 0,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7145,
      matchedOrders: 3541,
      pnlFromInitial: null,
      turnover: 2941056,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -78.03,
      cumulativePnlTotal: -1055.98,
      timestamp: '2024-09-29T00:00:00Z',
      pnl: -86.7,
      cumulativePNL: -830.33,
      pnlInvestment: 8.67,
      cumulativePnlInvestment: -225.65,
    },
    {
      rebalancing: {
        sold: 117129.79,
        sellOrders: 6,
        sellingBotNames: ['Test bot'],
        bought: 72433.79,
        buyOrders: 4,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 10,
        failures: 0,
        serviceOperations: 10,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 10,
            failures: 0,
            serviceOperations: 10,
          },
        ],
      },
      allOrders: 7029,
      matchedOrders: 3272,
      pnlFromInitial: null,
      turnover: 2059127,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 2703.6,
      cumulativePnlTotal: 1645.62,
      timestamp: '2024-09-30T00:00:00Z',
      pnl: 2488.12,
      cumulativePNL: 1656.79,
      pnlInvestment: 215.48,
      cumulativePnlInvestment: -11.17,
    },
    {
      rebalancing: {
        sold: 82593.99,
        sellOrders: 4,
        sellingBotNames: ['Test bot'],
        bought: 84931.1,
        buyOrders: 5,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 12,
        failures: 6,
        serviceOperations: 6,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 12,
            failures: 6,
            serviceOperations: 6,
          },
        ],
      },
      allOrders: 7383,
      matchedOrders: 3822,
      pnlFromInitial: null,
      turnover: 2754208,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 2642.65,
      cumulativePnlTotal: 4286.27,
      timestamp: '2024-10-01T00:00:00Z',
      pnl: 2449.09,
      cumulativePNL: 4104.88,
      pnlInvestment: 193.56,
      cumulativePnlInvestment: 181.39,
    },
    {
      rebalancing: {
        sold: 16194.43,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 49104.92,
        buyOrders: 3,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 0,
        serviceOperations: 4,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 4,
            failures: 0,
            serviceOperations: 4,
          },
        ],
      },
      allOrders: 2213,
      matchedOrders: 956,
      pnlFromInitial: null,
      turnover: 599416,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 194.12,
      cumulativePnlTotal: 4478.39,
      timestamp: '2024-10-02T00:00:00Z',
      pnl: 263.68,
      cumulativePNL: 4367.56,
      pnlInvestment: -69.56,
      cumulativePnlInvestment: 110.83,
    },
  ],
  aggregationPeriod: 'Daily',
};
