export const data = {
  data: [
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2023-11-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2023-12-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2024-01-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2024-02-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2024-03-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2024-04-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      pnl: 0,
      cumulativePNL: 0,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 0,
      cumulativePnlTotal: 0,
      timestamp: '2024-05-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 54242.73,
        sellOrders: 3,
        sellingBotNames: ['Test bot configuration 1'],
        bought: 140016.2,
        buyOrders: 4,
        buyingBotNames: ['Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 4,
        failures: 4,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot configuration 1',
            runs: 4,
            failures: 4,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 2142,
      matchedOrders: 1244,
      pnlFromInitial: null,
      pnl: 36.04,
      cumulativePNL: 36.04,
      turnover: 61333,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 36.04,
      cumulativePnlTotal: 36.04,
      timestamp: '2024-06-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 366093.39,
        sellOrders: 19,
        sellingBotNames: ['Test bot', 'Test bot configuration 1'],
        bought: 310245.04,
        buyOrders: 13,
        buyingBotNames: ['Test bot', 'Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 37,
        failures: 37,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 34,
            failures: 34,
            serviceOperations: 0,
          },
          {
            botName: 'Test bot configuration 1',
            runs: 3,
            failures: 3,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 21347,
      matchedOrders: 11770,
      pnlFromInitial: null,
      pnl: -3875.24,
      cumulativePNL: -3839.2,
      turnover: 1304479,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: -3875.24,
      cumulativePnlTotal: -3839.2,
      timestamp: '2024-07-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 371327.24,
        sellOrders: 21,
        sellingBotNames: ['Test bot'],
        bought: 267908.05,
        buyOrders: 17,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 42,
        failures: 42,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 40,
            failures: 40,
            serviceOperations: 0,
          },
          {
            botName: 'Test bot configuration 1',
            runs: 2,
            failures: 2,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 57961,
      matchedOrders: 30485,
      pnlFromInitial: null,
      pnl: 3504.07,
      cumulativePNL: -335.13,
      turnover: 4789327,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 0,
      cumulativePnlInvestment: 0,
      pnlTotal: 3504.07,
      cumulativePnlTotal: -335.13,
      timestamp: '2024-08-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 1351307.74,
        sellOrders: 61,
        sellingBotNames: ['Test bot', 'Test bot configuration 1'],
        bought: 1620254.1,
        buyOrders: 74,
        buyingBotNames: ['Test bot', 'Test bot configuration 1'],
      },
      keeperRuns: {
        totalRuns: 95,
        failures: 27,
        serviceOperations: 68,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 82,
            failures: 14,
            serviceOperations: 68,
          },
          {
            botName: 'Test bot configuration 1',
            runs: 12,
            failures: 12,
            serviceOperations: 0,
          },
          {
            botName: 'Test bot 2',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 83661,
      matchedOrders: 43192,
      pnlFromInitial: null,
      pnl: 45232.57,
      cumulativePNL: 44897.44,
      turnover: 27017978,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 280.63,
      cumulativePnlInvestment: 280.63,
      pnlTotal: 45513.2,
      cumulativePnlTotal: 45178.07,
      timestamp: '2024-09-01T00:00:00Z',
    },
    {
      rebalancing: {
        sold: 98788.42,
        sellOrders: 5,
        sellingBotNames: ['Test bot'],
        bought: 134036.02,
        buyOrders: 8,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 16,
        failures: 6,
        serviceOperations: 10,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 16,
            failures: 6,
            serviceOperations: 10,
          },
        ],
      },
      allOrders: 9596,
      matchedOrders: 4778,
      pnlFromInitial: null,
      pnl: 2710.76,
      cumulativePNL: 47608.2,
      turnover: 3353624,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlInvestment: 122.01,
      cumulativePnlInvestment: 158.62,
      pnlTotal: 2832.77,
      cumulativePnlTotal: 47766.82,
      timestamp: '2024-10-01T00:00:00Z',
    },
  ],
  aggregationPeriod: 'Monthly',
};
