export const data = {
  data: [
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 206,
      matchedOrders: 75,
      pnlFromInitial: null,
      turnover: 51624,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 38.32,
      cumulativePnlTotal: 38.32,
      timestamp: '2024-10-01T11:00:00Z',
      pnl: 26.82,
      cumulativePNL: 26.82,
      pnlInvestment: 11.5,
      cumulativePnlInvestment: 11.5,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 552,
      matchedOrders: 131,
      pnlFromInitial: null,
      turnover: 57500,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 68.28,
      cumulativePnlTotal: 104.61,
      timestamp: '2024-10-01T12:00:00Z',
      pnl: 51.23,
      cumulativePNL: 77.05,
      pnlInvestment: 17.05,
      cumulativePnlInvestment: 27.56,
    },
    {
      rebalancing: {
        sold: 25474.41,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 2,
        failures: 1,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 2,
            failures: 1,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 421,
      matchedOrders: 231,
      pnlFromInitial: null,
      turnover: 225418,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 953.53,
      cumulativePnlTotal: 1056.14,
      timestamp: '2024-10-01T13:00:00Z',
      pnl: 866.76,
      cumulativePNL: 942.81,
      pnlInvestment: 86.77,
      cumulativePnlInvestment: 113.33,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 22052.3,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 320,
      matchedOrders: 168,
      pnlFromInitial: null,
      turnover: 142705,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -8.31,
      cumulativePnlTotal: 1045.84,
      timestamp: '2024-10-01T14:00:00Z',
      pnl: 2.61,
      cumulativePNL: 944.43,
      pnlInvestment: -10.92,
      cumulativePnlInvestment: 101.41,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 23451.4,
        buyOrders: 2,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 3,
        failures: 2,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 3,
            failures: 2,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 223,
      matchedOrders: 72,
      pnlFromInitial: null,
      turnover: 70015,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 153.51,
      cumulativePnlTotal: 1197.34,
      timestamp: '2024-10-01T15:00:00Z',
      pnl: 148.17,
      cumulativePNL: 1091.59,
      pnlInvestment: 5.34,
      cumulativePnlInvestment: 105.75,
    },
    {
      rebalancing: {
        sold: 17071.24,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 372,
      matchedOrders: 244,
      pnlFromInitial: null,
      turnover: 190991,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 566.49,
      cumulativePnlTotal: 1761.83,
      timestamp: '2024-10-01T16:00:00Z',
      pnl: 509.67,
      cumulativePNL: 1600.26,
      pnlInvestment: 56.82,
      cumulativePnlInvestment: 161.57,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 308,
      matchedOrders: 231,
      pnlFromInitial: null,
      turnover: 237734,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 391.47,
      cumulativePnlTotal: 2151.31,
      timestamp: '2024-10-01T17:00:00Z',
      pnl: 378.52,
      cumulativePNL: 1977.78,
      pnlInvestment: 12.95,
      cumulativePnlInvestment: 173.53,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18089.56,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 171,
      matchedOrders: 80,
      pnlFromInitial: null,
      turnover: 22350,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -1.02,
      cumulativePnlTotal: 2148.28,
      timestamp: '2024-10-01T18:00:00Z',
      pnl: 6.44,
      cumulativePNL: 1983.22,
      pnlInvestment: -7.46,
      cumulativePnlInvestment: 165.06,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 576,
      matchedOrders: 321,
      pnlFromInitial: null,
      turnover: 278071,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 198.43,
      cumulativePnlTotal: 2344.71,
      timestamp: '2024-10-01T19:00:00Z',
      pnl: 180.74,
      cumulativePNL: 2162.96,
      pnlInvestment: 17.69,
      cumulativePnlInvestment: 181.75,
    },
    {
      rebalancing: {
        sold: 16844.63,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 1,
        serviceOperations: 0,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 1,
            serviceOperations: 0,
          },
        ],
      },
      allOrders: 487,
      matchedOrders: 287,
      pnlFromInitial: null,
      turnover: 239572,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 916.84,
      cumulativePnlTotal: 3259.55,
      timestamp: '2024-10-01T20:00:00Z',
      pnl: 801.52,
      cumulativePNL: 2963.48,
      pnlInvestment: 115.32,
      cumulativePnlInvestment: 296.07,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 319,
      matchedOrders: 253,
      pnlFromInitial: null,
      turnover: 210737,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -262.12,
      cumulativePnlTotal: 2995.43,
      timestamp: '2024-10-01T21:00:00Z',
      pnl: -224.67,
      cumulativePNL: 2737.82,
      pnlInvestment: -37.45,
      cumulativePnlInvestment: 257.61,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 260,
      matchedOrders: 173,
      pnlFromInitial: null,
      turnover: 91089,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 87.82,
      cumulativePnlTotal: 3081.26,
      timestamp: '2024-10-01T22:00:00Z',
      pnl: 68.19,
      cumulativePNL: 2805.01,
      pnlInvestment: 19.63,
      cumulativePnlInvestment: 276.25,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 358,
      matchedOrders: 289,
      pnlFromInitial: null,
      turnover: 239167,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -142.98,
      cumulativePnlTotal: 2936.28,
      timestamp: '2024-10-01T23:00:00Z',
      pnl: -125.85,
      cumulativePNL: 2678.16,
      pnlInvestment: -17.13,
      cumulativePnlInvestment: 258.12,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 208,
      matchedOrders: 132,
      pnlFromInitial: null,
      turnover: 60821,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -34.39,
      cumulativePnlTotal: 2899.89,
      timestamp: '2024-10-02T00:00:00Z',
      pnl: -21.61,
      cumulativePNL: 2655.55,
      pnlInvestment: -12.78,
      cumulativePnlInvestment: 244.34,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 12068.16,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 283,
      matchedOrders: 159,
      pnlFromInitial: null,
      turnover: 111770,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -53.36,
      cumulativePnlTotal: 2844.53,
      timestamp: '2024-10-02T01:00:00Z',
      pnl: -23.77,
      cumulativePNL: 2630.78,
      pnlInvestment: -29.59,
      cumulativePnlInvestment: 213.75,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 456,
      matchedOrders: 134,
      pnlFromInitial: null,
      turnover: 86127,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: -67.03,
      cumulativePnlTotal: 2775.5,
      timestamp: '2024-10-02T02:00:00Z',
      pnl: -50.66,
      cumulativePNL: 2579.12,
      pnlInvestment: -16.37,
      cumulativePnlInvestment: 196.38,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18612.55,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 306,
      matchedOrders: 124,
      pnlFromInitial: null,
      turnover: 88644,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 20.61,
      cumulativePnlTotal: 2794.11,
      timestamp: '2024-10-02T03:00:00Z',
      pnl: 34.74,
      cumulativePNL: 2612.85,
      pnlInvestment: -14.13,
      cumulativePnlInvestment: 181.26,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 161,
      matchedOrders: 113,
      pnlFromInitial: null,
      turnover: 53019,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 171.64,
      cumulativePnlTotal: 2963.75,
      timestamp: '2024-10-02T04:00:00Z',
      pnl: 142.32,
      cumulativePNL: 2754.17,
      pnlInvestment: 29.32,
      cumulativePnlInvestment: 209.58,
    },
    {
      rebalancing: {
        sold: 16194.43,
        sellOrders: 1,
        sellingBotNames: ['Test bot'],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 256,
      matchedOrders: 128,
      pnlFromInitial: null,
      turnover: 64918,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 20.57,
      cumulativePnlTotal: 2982.32,
      timestamp: '2024-10-02T05:00:00Z',
      pnl: 16.74,
      cumulativePNL: 2769.91,
      pnlInvestment: 3.83,
      cumulativePnlInvestment: 212.41,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 18424.22,
        buyOrders: 1,
        buyingBotNames: ['Test bot'],
      },
      keeperRuns: {
        totalRuns: 1,
        failures: 0,
        serviceOperations: 1,
        botRuns: [
          {
            botName: 'Test bot',
            runs: 1,
            failures: 0,
            serviceOperations: 1,
          },
        ],
      },
      allOrders: 320,
      matchedOrders: 94,
      pnlFromInitial: null,
      turnover: 81987,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 87.6,
      cumulativePnlTotal: 3067.93,
      timestamp: '2024-10-02T06:00:00Z',
      pnl: 110.52,
      cumulativePNL: 2879.44,
      pnlInvestment: -22.92,
      cumulativePnlInvestment: 188.49,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 223,
      matchedOrders: 72,
      pnlFromInitial: null,
      turnover: 52130,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 62.48,
      cumulativePnlTotal: 3128.39,
      timestamp: '2024-10-02T07:00:00Z',
      pnl: 62.4,
      cumulativePNL: 2940.83,
      pnlInvestment: 0.08,
      cumulativePnlInvestment: 187.56,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 2,
      cumulativePnlTotal: 3128.39,
      timestamp: '2024-10-02T08:00:00Z',
      pnl: 1,
      cumulativePNL: 2940.83,
      pnlInvestment: 1,
      cumulativePnlInvestment: 187.56,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 2,
      cumulativePnlTotal: 3128.39,
      timestamp: '2024-10-02T09:00:00Z',
      pnl: 1,
      cumulativePNL: 2940.83,
      pnlInvestment: 1,
      cumulativePnlInvestment: 187.56,
    },
    {
      rebalancing: {
        sold: 0,
        sellOrders: 0,
        sellingBotNames: [],
        bought: 0,
        buyOrders: 0,
        buyingBotNames: [],
      },
      keeperRuns: {
        totalRuns: 0,
        failures: 0,
        serviceOperations: 0,
        botRuns: [],
      },
      allOrders: 0,
      matchedOrders: 0,
      pnlFromInitial: null,
      turnover: 0,
      baseCommission: 0,
      quoteCommission: 0,
      alternateCommission: null,
      alternateCommissionAsset: null,
      baseCommissionEquivalent: 0,
      quoteCommissionEquivalent: 0,
      alternateCommissionEquivalent: null,
      totalCommissionEquivalent: 0,
      pnlTotal: 2,
      cumulativePnlTotal: 3128.39,
      timestamp: '2024-10-02T10:00:00Z',
      pnl: 1,
      cumulativePNL: 2940.83,
      pnlInvestment: 1,
      cumulativePnlInvestment: 187.56,
    },
  ],
  aggregationPeriod: 'Hourly',
};

console.log('>>>data', data);
