import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';
import type { IncomingMessage, ServerResponse } from 'node:http';

const SOURCES = [
  { name: 'core', url: 'https://ui-kit-core.web.app' },
  { name: 'fitness', url: 'https://ui-kit-fitness.web.app' },
  { name: 'infra-dash', url: 'https://ui-kit-infra-dash.web.app' },
] as const;

// Rich manifest format generated by @storybook/addon-mcp
type PropInfo = {
  type?: { name: string };
  description?: string;
  defaultValue?: { value: string } | string;
  required?: boolean;
};

type ComponentManifestEntry = {
  id: string;
  name: string;
  path?: string;
  import?: string;
  description?: string;
  stories?: Array<{ id: string; name: string; code?: string }>;
  reactDocgen?: {
    props?: Record<string, PropInfo>;
    description?: string;
  };
};

type ComponentManifest = {
  components: ComponentManifestEntry[];
};

// Fallback: minimal story index format
type StoryEntry = {
  id: string;
  title: string;
  name: string;
  type: 'story' | 'docs';
  tags?: string[];
};

async function fetchJson<T>(url: string): Promise<T | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
    if (!res.ok) return null;
    return res.json() as Promise<T>;
  } catch {
    return null;
  }
}

async function fetchManifest(
  baseUrl: string,
): Promise<ComponentManifestEntry[] | null> {
  const manifest = await fetchJson<ComponentManifest>(
    `${baseUrl}/manifests/components.json`,
  );
  return manifest?.components ?? null;
}

async function fetchIndex(
  baseUrl: string,
): Promise<Record<string, StoryEntry> | null> {
  const data = await fetchJson<{ entries?: Record<string, StoryEntry> }>(
    `${baseUrl}/index.json`,
  );
  return data?.entries ?? null;
}

function formatProp(name: string, info: PropInfo): string {
  const type = info.type?.name ?? 'unknown';
  const required = info.required ? ' (required)' : '';
  const defaultVal =
    info.defaultValue != null
      ? ` — default: ${typeof info.defaultValue === 'object' ? info.defaultValue.value : info.defaultValue}`
      : '';
  const desc = info.description ? ` — ${info.description}` : '';
  return `  - \`${name}\`: ${type}${required}${defaultVal}${desc}`;
}

function createServer() {
  const server = new McpServer({ name: 'ssa-ui-kit', version: '1.0.0' });

  server.tool(
    'list_components',
    'List all available UI components in the SSA UI Kit, grouped by package (core, fitness, infra-dash). Use this before writing any UI code to discover what components exist.',
    {},
    async () => {
      const lines: string[] = ['# SSA UI Kit — Available Components\n'];

      await Promise.all(
        SOURCES.map(async (src) => {
          // Prefer rich manifest, fall back to index.json
          const components = await fetchManifest(src.url);
          if (components) {
            if (components.length === 0) return;
            lines.push(`## ${src.name}`);
            for (const c of components) {
              const imp = c.import ? ` — \`${c.import}\`` : '';
              lines.push(`- **${c.name}**${imp}`);
            }
            lines.push('');
            return;
          }

          const entries = await fetchIndex(src.url);
          if (!entries) return;
          const seen = new Map<string, string[]>();
          for (const entry of Object.values(entries)) {
            if (entry.type !== 'story') continue;
            if (!seen.has(entry.title)) seen.set(entry.title, []);
            seen.get(entry.title)!.push(entry.name);
          }
          if (seen.size === 0) return;
          lines.push(`## ${src.name}`);
          for (const [title, stories] of seen) {
            lines.push(`- **${title}** — variants: ${stories.join(', ')}`);
          }
          lines.push('');
        }),
      );

      return {
        content: [{ type: 'text' as const, text: lines.join('\n') }],
      };
    },
  );

  server.tool(
    'get_component_docs',
    'Get props, import path, description, and story links for a specific SSA UI Kit component. Search by name before using it in code.',
    {
      query: z
        .string()
        .describe(
          'Component name to look up, e.g. "Button", "NumberField", or "Select"',
        ),
    },
    async ({ query }) => {
      const search = query.toLowerCase();
      const sections: string[] = [];

      await Promise.all(
        SOURCES.map(async (src) => {
          const components = await fetchManifest(src.url);
          if (components) {
            const matches = components.filter((c) =>
              c.name.toLowerCase().includes(search),
            );
            for (const c of matches) {
              const base = `https://uikit.ssa.group/?path=`;
              const lines: string[] = [`### ${c.name} (${src.name})`];

              if (c.import) lines.push(`**Import:** \`${c.import}\``);

              const desc = c.reactDocgen?.description ?? c.description;
              if (desc) lines.push(`**Description:** ${desc}`);

              const props = c.reactDocgen?.props;
              if (props && Object.keys(props).length > 0) {
                lines.push('**Props:**');
                for (const [name, info] of Object.entries(props)) {
                  lines.push(formatProp(name, info));
                }
              }

              if (c.stories && c.stories.length > 0) {
                lines.push('**Stories:**');
                for (const s of c.stories) {
                  lines.push(`  - ${s.name}: ${base}/story/${s.id}`);
                }
              }

              sections.push(lines.join('\n'));
            }
            return;
          }

          // Fallback to index.json
          const entries = await fetchIndex(src.url);
          if (!entries) return;
          const matched = new Map<string, StoryEntry[]>();
          for (const entry of Object.values(entries)) {
            if (!entry.title.toLowerCase().includes(search)) continue;
            if (!matched.has(entry.title)) matched.set(entry.title, []);
            matched.get(entry.title)!.push(entry);
          }
          for (const [title, items] of matched) {
            const stories = items.filter((e) => e.type === 'story');
            const docs = items.find((e) => e.type === 'docs');
            const base = `https://uikit.ssa.group/?path=`;
            const lines = [`### ${title} (${src.name})`];
            if (docs) lines.push(`- Docs: ${base}/docs/${docs.id}`);
            if (stories.length > 0) {
              lines.push('- Stories:');
              for (const s of stories) {
                lines.push(`  - ${s.name}: ${base}/story/${s.id}`);
              }
            }
            sections.push(lines.join('\n'));
          }
        }),
      );

      const text =
        sections.length > 0
          ? sections.join('\n\n')
          : `No component found matching "${query}"`;

      return {
        content: [{ type: 'text' as const, text }],
      };
    },
  );

  return server;
}

export default async function handler(
  req: IncomingMessage & { body?: unknown },
  res: ServerResponse,
) {
  const server = createServer();
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
  });

  res.on('close', () => {
    transport.close();
    server.close();
  });

  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
}
