name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Installing Node.js...
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      
      - name: Getting pnpm store directory...
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Restoring pnpm cache...
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies...
        run: pnpm -w install

      - name: Linting codebase...
        run: pnpm lint

      - name: Linting styles...
        run: pnpm lint:styles

      - name: Building packages...
        run: pnpm build:all

      - name: Running unit tests...
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm test:coverage

      - name: "Building storybook: Core"
        run: pnpm sb:build:core
        env:
          CI: true

      - name: Running Core storybook...
        run: pnpm sb:core &

      - name: Installing Playwright Browsers...
        run: |
          cd ./packages/core
          pnpm -w install
          npx playwright install chromium --with-deps
          cd ../..

      - name: Running e2e tests...
        run: pnpm test:core:e2e

      # - name: Running visual tests...
      #   uses: lost-pixel/lost-pixel@v3.6.0
      #   env:
      #     LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
      #     LOST_PIXEL_CONFIG_DIR: ./packages/core

      - name: "Building storybook: Widgets"
        run: pnpm sb:build:widgets

      - name: "Running storybook: Widgets"
        run: pnpm sb:widgets &

      - name: Installing Playwright Browsers...
        run: |
          cd ./packages/widgets
          pnpm -w install
          npx playwright install chromium --with-deps
          cd ../..

      - name: Running e2e tests...
        run: pnpm test:widgets:e2e

      # - name: Running visual tests...
      #   uses: lost-pixel/lost-pixel@v3.6.0
      #   env:
      #     LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
      #     LOST_PIXEL_CONFIG_DIR: ./packages/widgets

      - name: "Building storybook: Templates"
        run: pnpm sb:build:templates

      - name: "Running storybook: Templates"
        run: pnpm sb:templates &

      # - name: Installing Playwright Browsers...
      #   run: |
      #     cd ./packages/templates
      #     pnpm -w install
      #     npx playwright install chromium --with-deps
      #     cd ../..

      # - name: Running e2e tests...
      #   run: pnpm test:templates:e2e

      # - name: Running visual tests...
      #   uses: lost-pixel/lost-pixel@v3.6.0
      #   env:
      #     LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
      #     LOST_PIXEL_CONFIG_DIR: ./packages/templates

      - name: Installing firebase tools...
        run: curl -sL https://firebase.tools | bash

      - name: Installing Vercel CLI...
        run: pnpm i -g vercel@canary

      - name: "Deploying: storybook root"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm sb:deploy:root --yes --token=${{ env.VERCEL_TOKEN }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: "Deploying: storybook fitness"
        run: pnpm sb:deploy:fitness

      - name: "Deploying: storybook core"
        run: pnpm sb:deploy:core

      - name: "Deploying: storybook templates"
        run: pnpm sb:deploy:templates

      - name: "Deploying: fitness dashboard"
        run: pnpm deploy:dashboard

  # finalize:
  #   needs: [main]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Lost Pixel Finalize
  #       uses: lost-pixel/lost-pixel@v3.6.0
  #       env:
  #         LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
  #         LOST_PIXEL_CONFIG_DIR: ./packages/widgets
  #       with:
  #         FINALIZE: true
