name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {
              package: "packages/core",
              name: "Building storybook: Core",
              command: "pnpm sb:build:core",
            }
          - {
              package: "packages/widgets",
              name: "Building storybook: Widgets",
              command: "pnpm sb:build:widgets",
            }
    steps:
      - name: Checkout...
        uses: actions/checkout@v3

      - name: Installing Node.js...
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      
      - name: Getting pnpm store directory...
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Restoring pnpm cache...
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing dependencies...
        run: pnpm install

      - name: ${{ matrix.config.name }}
        run: ${{ matrix.config.command }}
        env:
          CI: true

      - name: Running visual tests...
        uses: lost-pixel/lost-pixel@v3.4.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
          LOST_PIXEL_CONFIG_DIR: ${{ matrix.config.package }}